:sparkles: immediately discard 10-bit color videos as they convert to green

diff --git a/auto-reencode-one b/auto-reencode-one
--- a/auto-reencode-one
+++ b/auto-reencode-one
@@ -37,6 +37,12 @@ function reencode()
   if test -z "$FORCE"; then
     MEDIAINFO="$(mediainfo "$filepath")"
     CODEC=$(echo "$MEDIAINFO" | grep -A5 Video | grep Format | grep -v Info | grep -v profile | awk '{print $3}' | tr '[:upper:]' '[:lower:]')
+    BIT_DEPTH=$(echo "$MEDIAINFO" | grep -i "bit depth" | awk '{print $4}')
+    if test "$BIT_DEPTH" -ne "8"; then
+      echo "Unable to reliabily re-encode '${filepath}': has bit depth: '$BIT_DEPTH'";
+      rm "$filepath"
+      exit 2
+    fi
     if test -z "$QUIET"; then
       clear_line
       echo -n "inspect: $SHORT"
